/*
 * Customer API
 * This is a customer API, it provides REST API for customer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rajdeepmukh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import javax.annotation.processing.Generated;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Customer
 */
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-27T15:01:41.112Z")
public class Customer {
  @SerializedName("customerId")
  private Integer customerId = null;

  @SerializedName("accountvalue")
  private BigDecimal accountvalue = null;

  @SerializedName("customerName")
  private String customerName = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("adress")
  private CustomerAdress adress = null;

  @SerializedName("contacts")
  private List<CustomerContacts> contacts = null;

  public Customer customerId(Integer customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(value = "")
  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public Customer accountvalue(BigDecimal accountvalue) {
    this.accountvalue = accountvalue;
    return this;
  }

   /**
   * Get accountvalue
   * @return accountvalue
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAccountvalue() {
    return accountvalue;
  }

  public void setAccountvalue(BigDecimal accountvalue) {
    this.accountvalue = accountvalue;
  }

  public Customer customerName(String customerName) {
    this.customerName = customerName;
    return this;
  }

   /**
   * Get customerName
   * @return customerName
  **/
  @ApiModelProperty(value = "")
  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public Customer active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Customer adress(CustomerAdress adress) {
    this.adress = adress;
    return this;
  }

   /**
   * Get adress
   * @return adress
  **/
  @ApiModelProperty(value = "")
  public CustomerAdress getAdress() {
    return adress;
  }

  public void setAdress(CustomerAdress adress) {
    this.adress = adress;
  }

  public Customer contacts(List<CustomerContacts> contacts) {
    this.contacts = contacts;
    return this;
  }

  public Customer addContactsItem(CustomerContacts contactsItem) {
    if (this.contacts == null) {
      this.contacts = new ArrayList<CustomerContacts>();
    }
    this.contacts.add(contactsItem);
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @ApiModelProperty(value = "")
  public List<CustomerContacts> getContacts() {
    return contacts;
  }

  public void setContacts(List<CustomerContacts> contacts) {
    this.contacts = contacts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.customerId, customer.customerId) &&
        Objects.equals(this.accountvalue, customer.accountvalue) &&
        Objects.equals(this.customerName, customer.customerName) &&
        Objects.equals(this.active, customer.active) &&
        Objects.equals(this.adress, customer.adress) &&
        Objects.equals(this.contacts, customer.contacts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, accountvalue, customerName, active, adress, contacts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    accountvalue: ").append(toIndentedString(accountvalue)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    adress: ").append(toIndentedString(adress)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

