/*
 * Customer API
 * This is a customer API, it provides REST API for customer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rajdeepmukh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Customer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * This is to create a request for customer&#39;s data
     *
     * This method is being used post the data in JSON mode. The data should be in the JSON format
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerPostTest() throws ApiException {
        Customer body = null;
        Integer response = api.customerPost(body);

        // TODO: test validations
    }
    
    /**
     * delete a scpeific customer with the ID.
     *
     * Deletes an existing customer from the app.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCustomerTest() throws ApiException {
        Integer customerId = null;
        Customer response = api.deleteCustomer(customerId);

        // TODO: test validations
    }
    
    /**
     * This is to read customer&#39;s data
     *
     * This method is being used to fetch the customer data in JSON mode. It can be be questioned by other controller or some other user  using this API as a service
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerTest() throws ApiException {
        Integer customerId = null;
        Customer response = api.getCustomer(customerId);

        // TODO: test validations
    }
    
    /**
     * update existing customer
     *
     * Updates an existing customer with the Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCustomerTest() throws ApiException {
        Customer body = null;
        Integer customerId = null;
        api.updateCustomer(body, customerId);

        // TODO: test validations
    }
    
}
